// <auto-generated />
using System;
using DataAccessLayer.Concrate;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220925165457_mig1")]
    partial class mig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityLayer.Concrate.Bolumler", b =>
                {
                    b.Property<int>("BolumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BolumIsmi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("BolumId");

                    b.ToTable("Bolumlers");
                });

            modelBuilder.Entity("EntityLayer.Concrate.CalismaSekli", b =>
                {
                    b.Property<int>("CalismaSekliId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CalismaSekliIsmi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("CalismaSekliId");

                    b.ToTable("CalismaSeklis");
                });

            modelBuilder.Entity("EntityLayer.Concrate.EgitimSeviyesi", b =>
                {
                    b.Property<int>("EgitimSeviyesiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EgitimSeviyesiIsmi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EgitimSeviyesiId");

                    b.ToTable("EgitimSeviyesis");
                });

            modelBuilder.Entity("EntityLayer.Concrate.Firmalar", b =>
                {
                    b.Property<int>("FirmaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirmaFoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirmaIsmi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("FirmaId");

                    b.ToTable("Firmalars");
                });

            modelBuilder.Entity("EntityLayer.Concrate.HesapTuru", b =>
                {
                    b.Property<int>("HesapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HesapTuruIsmi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HesapId");

                    b.ToTable("HesapTurus");
                });

            modelBuilder.Entity("EntityLayer.Concrate.IlanTuru", b =>
                {
                    b.Property<int>("IlanTuruId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IlanTuruIsim")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IlanTuruId");

                    b.ToTable("IlanTurus");
                });

            modelBuilder.Entity("EntityLayer.Concrate.IsIlanlari", b =>
                {
                    b.Property<int>("IlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("IlanIcerigi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IlanImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IlanIsmi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IlanTuru")
                        .HasColumnType("int");

                    b.Property<int>("PozisyonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("YayinlanmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("IlanId");

                    b.ToTable("IsIlanlaris");
                });

            modelBuilder.Entity("EntityLayer.Concrate.Kullanıcılar", b =>
                {
                    b.Property<int>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cinsiyet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DoğumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Eposta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HesapOlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("HesapTuru")
                        .HasColumnType("int");

                    b.Property<string>("KullaniciFoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TelefonNumarasi")
                        .HasColumnType("int");

                    b.HasKey("KullaniciId");

                    b.ToTable("Kullanıcılars");
                });

            modelBuilder.Entity("EntityLayer.Concrate.Ozgecmis", b =>
                {
                    b.Property<int>("OzgecmisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AskerlikDurumu")
                        .HasColumnType("int");

                    b.Property<string>("Cinsiyet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("EgitimSeviyesi")
                        .HasColumnType("int");

                    b.Property<string>("Eposta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurucuBelgesi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TelefonNumarası")
                        .HasColumnType("int");

                    b.Property<string>("Universite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UniversiteBolumu")
                        .HasColumnType("int");

                    b.HasKey("OzgecmisId");

                    b.ToTable("Ozgecmiss");
                });

            modelBuilder.Entity("EntityLayer.Concrate.Pozisyonlar", b =>
                {
                    b.Property<int>("PozisyonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PozisyonIsmi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("PozisyonId");

                    b.ToTable("Pozisyonlars");
                });

            modelBuilder.Entity("EntityLayer.Concrate.Sehirler", b =>
                {
                    b.Property<int>("SehirId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SehirIsmi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SehirId");

                    b.ToTable("Sehirlers");
                });

            modelBuilder.Entity("EntityLayer.Concrate.UniversiteBolumu", b =>
                {
                    b.Property<int>("UniversitBolumuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UniversiteBolumuIsmi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UniversitBolumuId");

                    b.ToTable("UniversiteBolumus");
                });
#pragma warning restore 612, 618
        }
    }
}
